# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: 'BuildAndDeploy'
  displayName: 'Build and deploy'
  jobs:
  - job: 'Build'
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.BuildDirectory)
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    # TODO: Use PublishPipelineArtifacts?
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Aurora'
        publishLocation: 'Container'

  - deployment: 'Run'
    environment: 'Aurora.auroravm'
    dependsOn: 'Build'

    strategy:
     runOnce:
       deploy:
         steps:
          # TODO: Use DownloadPipelineArtifacts?
          #- task: DownloadBuildArtifacts@0
          #  inputs:
          #    buildType: 'current'
          #    downloadType: 'single'
          #    artifactName: 'Aurora'
          #    downloadPath: '$(Agent.BuildDirectory)'

          - task: BatchScript@1
            inputs:
              filename: '$(Agent.BuildDirectory)/Aurora/s/bin/release/net6.0-windows/Aurora.exe'
              arguments: '$(Agent.BuildDirectory)/Aurora/s/Borealis.db'

          #- task: PowerShell@2
          #  inputs:
          #    targetType: 'filePath'
          #    filePath: '$(Agent.BuildDirectory)/Aurora/s/RunBorealis.ps1'
          #    workingDirectory: '$(Agent.BuildDirectory)/Aurora/s/'
